Controllers/song/songController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Google.GData;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.YouTube;
using Google.YouTube;


namespace hypster.Controllers
{
    public class songController : ControllerBase
    {
        //
        //no additional methods here since it will be traslated into song url /song/GUID
        //



        //----------------------------------------------------------------------------------------------------------
        // for song landing page
        //[OutputCache(Duration = 1200, VaryByParam = "none")]
        public ActionResult getSongByID(string song_guid)
        {
            // 1.general declarations
            //-----------------------------------------------------------------------------------------------------
            hypster_tv_DAL.songsManagement song_manager = new hypster_tv_DAL.songsManagement();
            hypster_tv_DAL.memberManagement memberManager = new hypster_tv_DAL.memberManagement();
            //-----------------------------------------------------------------------------------------------------

            int song_int_id = 0;
            if (Int32.TryParse(song_guid, out song_int_id) == false)
            {
                return RedirectPermanent("/");
            }


            // 2.get model
            //-----------------------------------------------------------------------------------------------------
            hypster.ViewModels.SongLandingPageViewModel songModel = new ViewModels.SongLandingPageViewModel();
            songModel.song = song_manager.GetSongByID(song_guid);

            songModel.songComments_list = song_manager.Get_SongComments(songModel.song.id);
            //-----------------------------------------------------------------------------------------------------


            return View(songModel);
        }
        //----------------------------------------------------------------------------------------------------------

        


    }
}

Controllers/song/songDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Google.GData;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.YouTube;
using Google.YouTube;

namespace hypster.Controllers
{
    public class songDetailsController : ControllerBase
    {



        //----------------------------------------------------------------------------------------------------------
        // song landing page dynamic content
        //
        public ActionResult GetSongDynamicDetails()
        {

            // 1.parse query string
            //-----------------------------------------------------------------------------------------------------
            string song_guid = "";
            if (Request.QueryString["song_guid"] != null)
            {
                song_guid = Request.QueryString["song_guid"];
            }
            //-----------------------------------------------------------------------------------------------------


            // 2.get video dynamic details
            //-----------------------------------------------------------------------------------------------------
            Video video = new Video();
            try
            {
                YouTubeRequestSettings settings = new YouTubeRequestSettings("hypster", "AI39si5TNjKgF6yiHwUhKbKwIui2JRphXG4hPXUBdlrNh4XMZLXu--lf66gVSPvks9PlWonEk2Qv9fwiadpNbiuh-9TifCNsqA");
                YouTubeRequest request = new YouTubeRequest(settings);
                string feedUrl = "http://gdata.youtube.com/feeds/api/videos/" + song_guid;
                video = request.Retrieve<Video>(new Uri(feedUrl));
            }catch(Exception ex){}
            //-----------------------------------------------------------------------------------------------------




            return View(video);
        }
        //----------------------------------------------------------------------------------------------------------








        //----------------------------------------------------------------------------------------------------------
        [HttpPost]
        public ActionResult PostSongComment(string songComment, string songGuid)
        {
            if (User.Identity.IsAuthenticated == false)
                return RedirectPermanent("/account/SignIn?ReturnUrl=/song/" + songGuid);


            hypster_tv_DAL.Hypster_Entities hyDB = new hypster_tv_DAL.Hypster_Entities();
            hypster_tv_DAL.songsManagement songManager = new hypster_tv_DAL.songsManagement();
            hypster_tv_DAL.memberManagement memberManager = new hypster_tv_DAL.memberManagement();

            hypster_tv_DAL.Song curr_song = new hypster_tv_DAL.Song();
            curr_song = songManager.GetSongByID(songGuid);



            hypster_tv_DAL.songComment p_comment = new hypster_tv_DAL.songComment();
            p_comment.song_ID = curr_song.id;

            p_comment.ipAddress = IpAddress();
            p_comment.status = (int)hypster_tv_DAL.newsCommentStatus.NoActive;
            p_comment.user_ID = memberManager.getMemberByUserName(User.Identity.Name).id;
            p_comment.userName = User.Identity.Name;
            p_comment.postDate = DateTime.Now;

            
            p_comment.comment = songComment;
            if(p_comment.comment.Length > 1990)
                p_comment.comment = p_comment.comment.Substring(0,1990);


            hyDB.songComments.AddObject(p_comment);
            hyDB.SaveChanges();


            return RedirectPermanent("/song/" + songGuid);
        }
        //----------------------------------------------------------------------------------------------------------













        //----------------------------------------------------------------------------------------------------------
        /// <summary>
        /// Service function - gives user ip address
        /// </summary>
        /// <returns></returns>
        private string IpAddress()
        {
            string strIpAddress;
            strIpAddress = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            if (strIpAddress == null) strIpAddress = Request.ServerVariables["REMOTE_ADDR"];
            return strIpAddress;
        }
        //----------------------------------------------------------------------------------------------------------





    }
}

Views/song/getSongByID.cshtml
@model hypster.ViewModels.SongLandingPageViewModel
@{
    ViewBag.Title = @Model.song.Title + " - Hypster";
    ViewBag.Desc = "";
}



<script type="text/javascript">
    $(document).ready(function () {
        RenderSong();
    });
    $(window).resize(function () {
        RenderSong();
    });
</script>





<div class="boxContRight boxContRightTop">
    <div id="listenSlide1" class="slideRight" style=" min-height:250px;">


            <div class="SongLandingCont">
                

                <div class="ImgCont">
                    <img src="http://i.ytimg.com/vi/@Model.song.YoutubeId/0.jpg" />
                </div>


                <div class="ItmDetailsCont">
                    
                    <div class="SongTitle">
                            @Model.song.Title
                    </div>


                    <div class="SongAddDetails">
                            <div class="witm">
                                Added: <span style=" color:#FCF088;"> @Model.song.adddate.ToShortDateString() </span>
                            </div>

                            <div class="witm">
                                Giud: <span style=" color:#FCF088;"> @Model.song.YoutubeId </span>
                            </div>

                            <div id="addDetailsContainer" class="witm"></div>
                    </div>



                    <div class="ActionsCont">
                            <div class="ActPlayBtn" onclick="OpenPlayer('song_guid=@Model.song.YoutubeId&song_title=@HttpUtility.UrlEncode(Model.song.Title)');">
                                <img alt="" src="/imgs/play_icon.png" style=" margin-top:9px;" />
                            </div>

                            <div class="AddPlayBtn" onclick="window.location='/listen?ss=@System.Web.HttpUtility.UrlEncode(Model.song.Title)';">
                                <img alt="" src="/imgs/search-music-icon.png" style=" margin-top:7px;" />
                            </div>
                    
                            <div class="ActAddBtn" onclick="ShowAddToMyPlaylist('?song_guid=@Model.song.YoutubeId&song_title=@System.Web.HttpUtility.UrlEncode(Model.song.Title)');">
                                <b>+</b> Add to Playlist
                            </div>
                    
                            <div class="ActGetRingtone">
                                <a href="http://www.funtonia.com/mp3ringtones/search.asp?sw=@Model.song.Title&affid=120674" target="_blank">Get Ringtone&nbsp;</a>
                            </div>
                    </div>


                </div>

            </div>
            

</div>
</div>






<div class="boxContLeft">
    <div id="listenSlide2" class="slideLeft" style=" min-height:300px;">
        

            <div class="SongCommentsCont">
            

                    <div class="CommHeader">
                        Comments
                    </div>


                    @using (Html.BeginForm("PostSongComment", "songDetails", FormMethod.Post))
                    {
                        <textarea id="songComment" name="songComment"></textarea>
                        <input type="hidden" id="songGuid" name="songGuid" value="@Model.song.id" />

                        <div class="CommSubmCont">
                            <input id="PostNewComm" type="submit" value="Post Comment"/>
                        </div>
                    }



                    @foreach (hypster_tv_DAL.songComment item in Model.songComments_list)
                    {
                        <div class="CommItm">
                            <div class="CommComment">
                                @item.comment
                            </div>

                            <div class="CommDate">
                                @item.userName, <span style="font-size:13px;">@item.postDate.ToString()</span>
                            </div>
                        </div>
                    }



                    <div style=" float:left; width:100%; margin-top:10px; ">

                        <div style="float:left; width:728px; height:90px; background-color:#858c90; border:3px solid #858c90; border-radius:2px;">
                            <div id="TopAdd1"></div>
                            <script type="text/javascript">
                                $(document).ready(function () {
                                    document.getElementById("TopAdd1").innerHTML = "<iframe width=\"728\" scrolling=\"no\" height=\"90\" frameborder=\"0\" style=\"border:none;\" marginwidth=\"0\" src=\"http://feed-rt.baronsoffers.com/offer/feed/q/aT0zNTQ4LHM9NzI4eDkwLG49aWZyYW1l?subid=default\"></iframe>";
                                });
                            </script>
                        </div>


                        <div onclick="window.location='http://@System.Configuration.ConfigurationManager.AppSettings["videoHostName"]/page/1';" style=" float:left; width:275px; height:90px; margin-left:15px; background-color:#858c90; border:3px solid #858c90; border-radius:2px; line-height:90px; text-align:center; font-size:27px; cursor:pointer;">
                            Hypster Videos
                        </div>

                    </div>



            </div>

    </div>
</div>









<script type="text/javascript">

    $(document).ready(function () {

        $.ajax({
            type: "POST",
            url: "/songDetails/GetSongDynamicDetails?song_guid=@Model.song.YoutubeId",
            async: true,
            success: function (data) {
                $('#addDetailsContainer').html(data);
            }
        });

    });

</script>