ViewModels/homeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace hypster.ViewModels
{

    public class homeViewModel
    {
        //public List<hypster_tv_DAL.videoClip> TopVideos = new List<hypster_tv_DAL.videoClip>();

        public List<hypster_tv_DAL.Song> most_popular_songs = new List<hypster_tv_DAL.Song>();

        public List<hypster_tv_DAL.VisualSearch> visualSearch_list = new List<hypster_tv_DAL.VisualSearch>();



        public homeViewModel()
        {
        }




    }

}

Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace hypster.Controllers
{
    public class homeController : ControllerBase
    {
        //
        // GET: /home/

        public ActionResult Index()
        {
            //hypster.ViewModels.homeViewModel model = new ViewModels.homeViewModel();

            //hypster_tv_DAL.songsManagement songManager = new hypster_tv_DAL.songsManagement();
            //model.most_popular_songs = songManager.Get_MostPopularSong_Random();
            //hypster_tv_DAL.visualSearchManager visualSearchManager = new hypster_tv_DAL.visualSearchManager();
            //model.visualSearch_list = visualSearchManager.getVisualSearchArtists_cached();
            //return View(model);

            return View();
        }



        [OutputCache(Duration = 240, VaryByParam = "none")]
        public ActionResult visualSearchBar()
        {
            hypster_tv_DAL.visualSearchManager visualSearchManager = new hypster_tv_DAL.visualSearchManager();
            List<hypster_tv_DAL.VisualSearch> model = visualSearchManager.getVisualSearchArtists_cached();


            return View(model);
        }



        [OutputCache(Duration = 240, VaryByParam = "none")]
        public ActionResult Get_MostPopularSong_Random()
        {
            hypster_tv_DAL.songsManagement songManager = new hypster_tv_DAL.songsManagement();
            List<hypster_tv_DAL.Song> model = songManager.Get_MostPopularSong_Random();


            return View(model);
        }


    }
}

Views/home/Get_MostPopularSong_Random.cshtml
@model List<hypster_tv_DAL.Song>
@{
    Layout = null;
}


@{
    int back_id = 1;
}
@for(int i=1; i<=13; i++)
{
    if( i < Model.Count)
    {
        <div @if (back_id == 1) { <text>class="songItm"</text>} else {<text>class="songItm1"</text>}>
            <a class="songItm_title" href="/song/@Model[i - 1].id">@(i). @Model[i - 1].Title</a>
            <a class="songItm_play" title="play" onclick="OpenPlayer('song_guid=@Model[i - 1].YoutubeId&song_title=@HttpUtility.UrlEncode(Model[i - 1].Title)');"></a>
        </div>
    }
    back_id = back_id * -1;
}

Views/home/Index.cshtml
@{
    ViewBag.Title = "Free music online - Playlist and player for tumblr | Hypster ";
    ViewBag.Desc = "Search songs, make a playlist online for free, create player for tumblr or blogger, listen to youtube music, create your own playlist online for free.";
    ViewBag.ActivePage = "hypster";
}
@Scripts.Render("~/scripts/jquery.cycle.all.latest.js")


<script type="text/javascript">
    active_menu = ".mHypster";
    $(".mHypster").css("background-color", "#191919");

    $(document).ready(function () {
        RenderHome();
    });
    $(window).resize(function () {
        RenderHome();
    });
    $(document).ready(function () {
        setTimeout('StartSlideshow()', 2000);
    });
</script>






<div class="boxContRight boxContRightTop">
    <div id="listenSlide1" class="slideRight" style=" min-height:480px;">


            <div class="sld1_topCont">
        
                    <div class="topLeft">

                        <div class="mainSlideshow">
                            
                            <!--div id="HomeSlide1">
                                <img alt="" src="/imgs/home/main_slide_4.jpg" onclick="window.location='/hypster/New_Player_For_Tumblr';" />
                                <div class="SlideshowBultesCont">
                                    <div class="slideBuletSel" onclick="opnSlide('1');"></div>
                                    <div class="slideBulet" onclick="opnSlide('2');"></div>
                                    <div class="slideBulet" onclick="opnSlide('3');"></div>
                                </div>
                            </div-->


                            <div id="HomeSlide2">
                                <img alt="" src="/imgs/home/main_slide_3.jpg" onclick="window.location='/hypster/Hypster_On_Mobile';" />
                                <div class="SlideshowBultesCont">
                                    <!--div class="slideBulet" onclick="opnSlide('1');"></div-->
                                    <div class="slideBuletSel" onclick="opnSlide('2');"></div>
                                    <div class="slideBulet" onclick="opnSlide('3');"></div>
                                </div>
                            </div>


                            <div id="HomeSlide3">
                                <img alt="" src="/imgs/home/main_slide_1.jpg" onclick="window.location='/hypster/How_To_Use';" />
                                <div class="SlideshowBultesCont">
                                    <!--div class="slideBulet" onclick="opnSlide('1');"></div-->
                                    <div class="slideBulet" onclick="opnSlide('2');"></div>
                                    <div class="slideBuletSel" onclick="opnSlide('3');"></div>
                                </div>
                            </div>

                        </div>
                        

                    </div>


                    <div class="topRight">
                        <!-- BEGIN TAG - DO NOT MODIFY -->
                        <script type="text/javascript">
                        <!--
                            epom_key = "fb09543b2a19872f1a4246b5ee450dda";
                            epom_code_format = "ads-api-sync.js";
                            epom_click = "";
                            epom_custom_params = {};

                            document.write("<script type='text\/javascript' src='" + (location.protocol == 'https:' ? 'https:' : 'http:') + "//www.adshost2.com\/js/show_ads.js'><\/script>");
                        //-->
                        </script>

                    </div>

            </div>



            <div id="listenSlide1_textBoxes" class="sld1_middleCont">
        
                    <div class="middleC1">
                        <div class="head11">Music for Free</div>
                        <div class="cont21">Listen to millions of songs available to you for free. Uncover a great range of songs from our vast library of music.</div>
                    </div>

                    <div class="middleC2">
                        <div class="head11">Your Music on Your Site</div>
                        <div class="cont21">Your playlist and post your songs on any site with your customizable player.</div>
                    </div>

                    <div class="middleC3">
                        <div class="head11">Social Experience</div>
                        <div class="cont21">Connect wtih friends, share songs and generate a community of followers.</div>
                    </div>

            </div>



            <div class="sld1_bottomCont">
                <div class="sld1_bottomContInnr">
                    
                        <input type="text" id="txtSearchString" name="txtSearchString" onKeyUp="SearchString_KeyUp(event)" value=" Enter Artist, Song or Genre"  onfocus="if(this.value == ' Enter Artist, Song or Genre') this.value = '';" onblur="if(this.value == '') this.value = ' Enter Artist, Song or Genre';" />
                        <div id="btnSearch" onclick="StartMusicSearch()"></div>
                        @Html.Action("visualSearchBar", "home")

                </div>
            </div>



    </div>
</div>







<div class="boxContLeft">
    <div id="listenSlide2" class="slideLeft" style=" min-height:450px;">
            @Html.Action("PopularVideos", "popular")
    </div>
</div>






<div class="boxContRight">
    <div id="listenSlide3" class="slideRight" style=" min-height:600px;">
        
            <div class="popularHomeContHolder" style=" width:300px; overflow:hidden;">
                <div class="popularHomeInner">
                        <div class="headerCont"><div>Popular on Hypster</div></div>
                        @Html.Action("Get_MostPopularSong_Random", "home")
                </div>
            </div>


            <div class="popularHomeAdCont" style=" width:300px; margin-left:6px;">
                <!-- BEGIN TAG - DO NOT MODIFY -->
                <script type="text/javascript">
                <!--
                    epom_key = "4c26cbe0a244cec198cfdf5827652955";
                    epom_code_format = "ads-api-sync.js";
                    epom_click = "";
                    epom_custom_params = {};

                    document.write("<script type='text\/javascript' src='" + (location.protocol == 'https:' ? 'https:' : 'http:') + "//www.adshost2.com\/js/show_ads.js'><\/script>");
                //-->
                </script>
                <!-- END TAG -->
            </div>


            <div id="listenSlide3_cont">
                @Html.Action("GetLatestNews", "news")
            </div>

    </div>
</div>

Views/home/visualSearchBar.cshtml
@model List<hypster_tv_DAL.VisualSearch>
@{
    Layout = null;
}

<div id="listenSlide1_search">
    <div id="VisualSHolder">
    @for (int i = 0; i < 50; i++)
    {
        if (i < Model.Count)
        {
            <img class="VisualS_itm" title="click to search for @Model[i].Artist_Name.Replace("_"," ")" alt="@Model[i].Artist_Name.Replace("_"," ")" src="/imgs/visualSearch/@(Model[i].Artist_Name).jpg" onclick="window.location='/listen?ss=@Model[i].Artist_Name.Replace("_","+")';" />
        }
    }
    </div>
</div>