ViewModels/AddToPlayListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace hypster.ViewModels
{
    public class AddToPlayListViewModel
    {

        public List<hypster_tv_DAL.PlaylistData_Song> songs_list = new List<hypster_tv_DAL.PlaylistData_Song>();
        public List<hypster_tv_DAL.Playlist> playlists_list = new List<hypster_tv_DAL.Playlist>();
        public hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();


        public AddToPlayListViewModel()
        {
        }


        
    }
}

Controllers/playlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Google.GData;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.YouTube;
using Google.YouTube;


namespace hypster.Controllers
{
    //
    //this controller is for playlist management
    public class playlistController : ControllerBase
    {


        //----------------------------------------------------------------------------------------------------------
        //authentitication implemented inside (ajax call)
        public ActionResult AddToPlayList()
        {
            //--------------------------------------------------------------------------------------------
            if (User.Identity.IsAuthenticated == false)
                return Content("<script type='text/javascript'>window.location='/account/SignIn';</script>");
            //--------------------------------------------------------------------------------------------



            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.memberManagement userManager = new hypster_tv_DAL.memberManagement();
            //--------------------------------------------------------------------------------------------




            //--------------------------------------------------------------------------------------------
            hypster.ViewModels.AddToPlayListViewModel model = new ViewModels.AddToPlayListViewModel();

            //get curr user
            hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();
            curr_user = userManager.getMemberByUserName(User.Identity.Name);


            if (Request.QueryString["song_title"] != null)
                ViewBag.song_title = Request.QueryString["song_title"];

            if (Request.QueryString["song_guid"] != null)
                ViewBag.song_guid = Request.QueryString["song_guid"];

            if (Request.QueryString["ss"] != null)
                ViewBag.ss = Request.QueryString["ss"];


            int PLAYLIST_ID = 0;
            PLAYLIST_ID = curr_user.active_playlist;

            hypster_tv_DAL.playlistManagement playlistManager = new hypster_tv_DAL.playlistManagement();
            model.songs_list = playlistManager.GetSongsForPlayList(curr_user.id, PLAYLIST_ID);

            model.playlists_list = playlistManager.GetUserPlaylists(curr_user.id);

            model.curr_user = curr_user;
            //--------------------------------------------------------------------------------------------




            // NEED TO CHECK HERE
            //--------------------------------------------------------------------------------------------
            foreach (var item in model.playlists_list)
            {
                if (PLAYLIST_ID == item.id)
                {
                    ViewBag.Playlist_ID = item.id;
                    ViewBag.Playlist_Name = item.name;
                }
            }
            //--------------------------------------------------------------------------------------------




            return View(model);
        }
        //----------------------------------------------------------------------------------------------------------




        //----------------------------------------------------------------------------------------------------------
        //authentitication implemented inside (ajax call)
        public ActionResult AddToPlayListPopup()
        {
            //--------------------------------------------------------------------------------------------
            if (User.Identity.IsAuthenticated == false)
                return Content("");
            //--------------------------------------------------------------------------------------------



            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.memberManagement userManager = new hypster_tv_DAL.memberManagement();
            //--------------------------------------------------------------------------------------------




            //--------------------------------------------------------------------------------------------
            hypster.ViewModels.AddToPlayListViewModel model = new ViewModels.AddToPlayListViewModel();

            //get curr user
            hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();
            curr_user = userManager.getMemberByUserName(User.Identity.Name);


            if (Request.QueryString["song_title"] != null)
                ViewBag.song_title = Request.QueryString["song_title"];

            if (Request.QueryString["song_guid"] != null)
                ViewBag.song_guid = Request.QueryString["song_guid"];


            int PLAYLIST_ID = 0;
            PLAYLIST_ID = curr_user.active_playlist;

            hypster_tv_DAL.playlistManagement playlistManager = new hypster_tv_DAL.playlistManagement();
            model.songs_list = playlistManager.GetSongsForPlayList(curr_user.id, PLAYLIST_ID);

            model.playlists_list = playlistManager.GetUserPlaylists(curr_user.id);

            model.curr_user = curr_user;
            //--------------------------------------------------------------------------------------------




            // NEED TO CHECK HERE
            //--------------------------------------------------------------------------------------------
            foreach (var item in model.playlists_list)
            {
                if (PLAYLIST_ID == item.id)
                {
                    ViewBag.Playlist_ID = item.id;
                    ViewBag.Playlist_Name = item.name;
                }
            }
            //--------------------------------------------------------------------------------------------




            return View(model);
        }
        //----------------------------------------------------------------------------------------------------------











        //----------------------------------------------------------------------------------------------------------
        [Authorize]
        [HttpPost]
        public ActionResult SubmitAddNewSong(string Song_Title, string Song_Guid, int? Sel_Playlist_ID, int? StayHereCheck, string ss)
        {

            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.Hypster_Entities hypDB = new hypster_tv_DAL.Hypster_Entities();
            hypster_tv_DAL.songsManagement songsManager = new hypster_tv_DAL.songsManagement();
            hypster_tv_DAL.memberManagement userManager = new hypster_tv_DAL.memberManagement();
            hypster_tv_DAL.playlistManagement playlistManagement = new hypster_tv_DAL.playlistManagement();
            //--------------------------------------------------------------------------------------------



            //get curr user
            //-----------------------------------------------------------------------------------------
            hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();
            curr_user = userManager.getMemberByUserName(User.Identity.Name);
            //-----------------------------------------------------------------------------------------




            //check if user has default playlist
            //-----------------------------------------------------------------------------------------
            if (curr_user.active_playlist == 0)
            {
                hypster_tv_DAL.Playlist create_playlist = new hypster_tv_DAL.Playlist();
                create_playlist.name = curr_user.username + "'s playlist";
                create_playlist.userid = curr_user.id;


                if (create_playlist.name.Length > 60)
                    create_playlist.name = create_playlist.name.Substring(0, 60);


                hypDB.Playlists.AddObject(create_playlist);
                hypDB.SaveChanges();

                List<hypster_tv_DAL.Playlist> playlists_list = playlistManagement.GetUserPlaylists(curr_user.id);
                if (playlists_list.Count > 0)
                {
                    curr_user.active_playlist = playlists_list[0].id;
                    userManager.SetUserDefaultPlaylist(User.Identity.Name, curr_user.id, curr_user.active_playlist);
                }
                //else error - need to have dafult playlist
            }
            //-----------------------------------------------------------------------------------------




            //check if user selected playlist
            //-----------------------------------------------------------------------------------------
            if (Sel_Playlist_ID == null || Sel_Playlist_ID == 0)
            {
                Sel_Playlist_ID = curr_user.active_playlist;
            }
            //-----------------------------------------------------------------------------------------





            // get last sort_number
            //-----------------------------------------------------------------------------------------
            short Sel_Sort_Order = 0;
            //List<hypster_tv_DAL.PlaylistData_Song> songs_list = new List<hypster_tv_DAL.PlaylistData_Song>();
            //songs_list = playlistManagement.GetSongsForPlayList(curr_user.id, (int)Sel_Playlist_ID);
            //if (songs_list.Count > 0)
            //{
            //    Sel_Sort_Order = songs_list[0].sortid;
            //    for (int i = 0; i < songs_list.Count; i++)
            //    {
            //        if (songs_list[i].sortid > Sel_Sort_Order)
            //            Sel_Sort_Order = songs_list[i].sortid;
            //    }
            //}
            //Sel_Sort_Order += 1;

            playlistManagement.IncrementPlaylistSongOrder(curr_user.id, (int)Sel_Playlist_ID);

Views/playlist/AddToPlayList.cshtml
@model hypster.ViewModels.AddToPlayListViewModel
@{
    Layout = null;
}



<script type="text/javascript">

    $(document).ready(function () {
        $("#AddToPlaylistCont1").css("display", "block");
        $("#AddToPlaylistCont1").css("margin-left", (($(document).width() - 850) / 2) + "px");
    });

</script>





<div id="AddToPlaylistCont1">
    

    <div class="ExitBtnCont">
        <img alt="" src="/imgs/exit_button.png" onclick="HideAddToPlaylist();" />
    </div>




    <div class="LeftCont">
    
            <div class="LeftContInnr">
            @using (Html.BeginForm("SubmitAddNewSong", "playlist", FormMethod.Post))
            {
                <h2 class="SongTitle">
                    @ViewBag.song_title
                </h2>
            
        
                <div class="SongDetails">
            
                    <img class="SongImg" alt="" src="http://i.ytimg.com/vi/@ViewBag.song_guid/default.jpg" />
            

                    <div style=" float:left; width:290px; line-height:31px; margin-left:10px; text-align:right; ">
                        Song ID: <input type="text" value="@ViewBag.song_guid" disabled="disabled" style=" width:210px; height:19px;" /><br />
                        Title: <input type="text" value="@ViewBag.song_title" disabled="disabled" style=" width:210px; height:19px; margin-top:2px;" /><br />
                        Playlist: 
                        <select id="Sel_Playlist_ID" name="Sel_Playlist_ID" style=" width:215px; height:26px; margin-top:2px;" onchange="playlist_changed_addToPlaylist(this);"> 
                            @foreach (var item in Model.playlists_list)
                            {
                                <option value="@item.id" @if(Model.curr_user.active_playlist == item.id){<text>selected="selected"</text>}>@item.name</option>
                            }
                        </select>

                        <input id="Song_Guid" name="Song_Guid" type="hidden" value="@ViewBag.song_guid" />
                        <input id="Song_Title" name="Song_Title" type="hidden" value="@ViewBag.song_title" />
                        <input id="ss" name="ss" type="hidden" value="@ViewBag.ss" />

                        <input id="StayHereCheck" name="StayHereCheck" type="hidden" value="" />
                    </div>
                </div>
        
        

                <div class="SongVerCont">
            
                    <div class="VerSong" onclick="OpenPlayer('song_guid=@ViewBag.song_guid&song_title=@HttpUtility.UrlEncode(ViewBag.song_title)');">
                        <img alt="" src="/imgs/attention_icon.png" style=" margin-top:2px;" />
                        Verify if song allowed on hypster
                    </div>
            
                
                    <a class="VerSongExt" href="http://hyptest.tumblr.com/?PL_ID=" target="_blank">
                        <img alt="" src="/imgs/attention_icon.png" style=" margin-top:2px;" />
                        Verify if song allowed on external domain websites
                    </a>

                </div>
        
        
                <div style="float:left; width:100%; margin-top:10px; text-align:right;">
                    <input class="AddBtn1" type="submit" value="ADD AND GO TO MY PLAYLIST" onclick="Add_and_go_to_CLICK();" />
                    <input class="AddBtn2" type="submit" value="ADD AND GET MORE" onclick="Add_and_stay_here_CLICK();" />
                </div>
            
            }
            </div>
        
    </div>


    



    <div class="RightCont">
    
            <div id="PlaylistContHoder1">

                <div class="PlaylistTitle">
                    @ViewBag.Playlist_Name
                </div>
            
                @foreach (var item in Model.songs_list)
                {
                    <div class="PlaylistItm">
                        <div onclick="OpenPlayer('song_guid=@item.YoutubeId&song_title=@HttpUtility.UrlEncode(item.Title)');">
                            <text>&nbsp;</text>@item.Title
                        </div>
                    </div>
                }
            </div>

    </div>




</div>




<script type="text/javascript">
    function Add_and_stay_here_CLICK() {
        $('#StayHereCheck').val('1');
        $('.AddBtn2').attr('value', 'Please wait...');
    }
    function Add_and_go_to_CLICK() {
        $('.AddBtn1').attr('value', 'Please wait...');
    }

    function playlist_changed_addToPlaylist(object) {
        
        $.ajax({
            type: "POST",
            url: "/playlist/getPlaylistDetails?PL_ID=" + object[object.selectedIndex].value,
            async: true,
            success: function (data) {
                $('#PlaylistContHoder1').html(data);
            }
        });

    }

    function HideAddToPlaylist() {
        document.getElementById('HideBackDiv').style.display = 'none';
        document.getElementById('popupContainer').style.display = 'none';
        $('#popupContainer').html("");
    }

</script>

Views/playlist/AddToPlayListPopup.cshtml
@model hypster.ViewModels.AddToPlayListViewModel
@{
    Layout = null;
}



<script type="text/javascript">

    $(document).ready(function () {
        $("#AddToPlaylistContPopup1").css("display", "block");
        $("#AddToPlaylistContPopup1").css("margin-left", (($(document).width() - 870) / 2) + "px");
    });

    function AddNewSongOnComplete() {
        
        if ($('#MessageBox1').html() == "SUCCESS") {
            HideAddToPlaylist();
            $('#MainContHolder').css('display', 'block');
        }
    }
    
</script>





<div id="AddToPlaylistContPopup1">
    

    <div class="ExitBtnCont">
        <img alt="" src="/imgs/exit_button.png" onclick="HideAddToPlaylist();" />
    </div>


    <div class="LeftCont">
    
            <div style=" float:left; width:98%; margin:1%; ">
            @using (Ajax.BeginForm("SubmitAddNewSongPopup", "playlist", new AjaxOptions { UpdateTargetId = "MessageBox1", HttpMethod = "POST", OnComplete = "AddNewSongOnComplete" }))
            {
                <h2 class="SongTitle">
                    @ViewBag.song_title
                </h2>
            
        
                <div class="SongDetails">
            
                    <img class="SongImg" alt="" src="http://i.ytimg.com/vi/@ViewBag.song_guid/default.jpg" />
            

                    <div style=" float:left; width:290px; line-height:31px; margin-left:10px; text-align:right; ">
                        Song ID: <input type="text" value="@ViewBag.song_guid" disabled="disabled" style=" width:210px; height:19px;" /><br />
                        <!--Title: <input type="text" value="@ViewBag.song_title" disabled="disabled" style=" width:210px; height:19px; margin-top:2px;" /--><br />
                        Playlist: 
                        <select id="Sel_Playlist_ID" name="Sel_Playlist_ID" style=" width:215px; height:26px; margin-top:2px;" onchange="playlist_changed_addToPlaylist(this);"> 
                            @foreach (var item in Model.playlists_list)
                            {
                                <option value="@item.id" @if(Model.curr_user.active_playlist == item.id){<text>selected="selected"</text>}>@item.name</option>
                            }
                        </select>

                        <input id="Song_Guid" name="Song_Guid" type="hidden" value="@ViewBag.song_guid" />
                        <input id="Song_Title" name="Song_Title" type="hidden" value="@ViewBag.song_title" />

                        <input id="StayHereCheck" name="StayHereCheck" type="hidden" value="" />
                    </div>
                </div>
        
        
        
                <div style="float:left; width:100%; margin-top:10px; text-align:right;">
                    <input class="AddBtn1" type="submit" value="ADD TO MY PLAYLIST" onmousedown="this.value='In Progress...';" />
                </div>
            
            
                <div id="MessageBox1"></div>
            }
            </div>
        
    </div>


    



    <div class="RightCont">
    
            <div id="PlaylistContHoder1">

                <div class="PlaylistTitle">
                    @ViewBag.Playlist_Name
                </div>
            
                @foreach (var item in Model.songs_list)
                {
                    <div class="PlaylistItm">
                        <div onclick="OpenPlayer('song_guid=@item.YoutubeId&song_title=@HttpUtility.UrlEncode(item.Title)');">
                            <text>&nbsp;</text>@item.Title
                        </div>
                    </div>
                }

            </div>

    </div>



    


</div>





<script type="text/javascript">
    function Add_and_stay_here_CLICK() {
        $('#StayHereCheck').val('1');
    }

    function playlist_changed_addToPlaylist(object) {
        
        $.ajax({
            type: "POST",
            url: "/playlist/getPlaylistDetails?PL_ID=" + object[object.selectedIndex].value,
            async: true,
            success: function (data) {
                $('#PlaylistContHoder1').html(data);
            }
        });

    }


    function HideAddToPlaylist() {
        Show_Content_PopupPlayer();
    }

</script>

Views/playlist/getPlaylistDetails.cshtml
@model List<hypster_tv_DAL.PlaylistData_Song>
@{
    Layout = null;
}





<div style=" float:left; width:100%; text-align:left; color:#FCF088; font-size:17px;">
    @ViewBag.Playlist_Name
</div>


@foreach (var item in Model)
{                  
    <div style=" float:left; width:100%; text-align:left;">

        <div onclick="OpenPlayer('song_guid=@item.YoutubeId&song_title=@HttpUtility.UrlEncode(item.Title)');" style=" float:left; width:99%; height:25px; line-height:25px; overflow:hidden; background-color:#454545; margin-left:1%; margin-top:3px; border-radius:2px; cursor:pointer; ">
            <text>&nbsp;</text>@item.Title
        </div>
    </div>
}



@if (Model.Count == 0)
{
    <div style="float:left; width:98%; height:23px; line-height:23px; overflow:hidden; margin:0px 4px 3px 4px; padding-left:3px; background-color:#454545; border-radius:2px; text-align:left; cursor:pointer; ">
        No songs in this playlist
    </div>
}

Views/playlist/getPlaylistDetailsEdt.cshtml
@model List<hypster_tv_DAL.PlaylistData_Song>
@{
    Layout = null;
}



<div id="sortablePlaylist">
@foreach (var item in Model)
{                  
    <div class="srt_itm" id="song_@item.playlist_track_id" style=" float:left; width:100%; text-align:left;" >
        
        <div title="play" onclick="OpenPlayer('song_guid=@item.YoutubeId&song_title=@HttpUtility.UrlEncode(item.Title)');" style=" float:left; width:25px; height:25px; line-height:30px; text-align:center; color:#FFFFFF; font-size:11px; background-color:#353535; border-radius:2px; margin-top:3px; margin-left:4px; cursor:pointer;">
            <img alt="play" src="/imgs/play_icon.png" style=" margin-top:7px;" />
        </div>

        <div onmouseup="isMOUSE_UP_ON = true;" onmousedown="mouse_down($('#song_@item.playlist_track_id'));" onmouseout="mouse_up($('#song_@item.playlist_track_id'), '@item.playlist_track_id' );" style=" float:left; width:360px; height:25px; line-height:25px; overflow:hidden; background-color:#454545; margin-left:5px; margin-top:3px; border-radius:2px; cursor:pointer; ">
            <text>&nbsp;</text>@item.Title
        </div>

        <div title="delete song" onclick="if(confirm('Are you sure you want to delete?') == true){ delete_song_playlist(@item.playlist_track_id);}" style=" float:left; height:25px; line-height:30px; text-align:left; color:#FFFFFF; font-size:11px; background-color:#353535; border-radius:2px; margin-top:3px; margin-left:1%; cursor:pointer;">
            <img alt="delete song" src="/imgs/action_icons/delete_icon_s.png" style=" margin:3px 7px 0 7px;" />
        </div>
    </div>
}
</div>








@if (Model.Count == 0)
{
    <div style="float:left; width:98%; height:23px; line-height:23px; overflow:hidden; margin:0px 4px 3px 4px; padding-left:3px; background-color:#454545; border-radius:2px; text-align:left; cursor:pointer; ">
        No songs in this playlist
    </div>
}
else
{
    <!--div style=" float:left; width:100%; text-align:left;">
        <a href="http://hyptest.tumblr.com/?PL_ID=@ViewBag.Playlist" target="_blank" style=" display:block; float:right; width:55%; height:25px; line-height:25px; text-align:center; color:#FCF088; font-size:13px; background-color:#555555; border-radius:2px; margin-top:3px; margin-left:4px; cursor:pointer;">
            Verify playlist on Thumblr
        </a>
    </div-->
}





<script type="text/javascript">
    function delete_song_playlist(song_id) {
        
        $.ajax({
            type: "POST",
            url: "/playlist/deletePlaylistSong?SONG_ID=" + song_id,
            async: true,
            success: function (data) {
                if (data == "true") {
                    $("#song_" + song_id).css("display", "none");
                }
            }
        });

    }
</script>





<style>    
    #sortablePlaylist { list-style-type:none; margin: 0; padding: 0; float:left; width:100%; }    
    #sortablePlaylist .srt_itm { float:left; }
</style>

<script type="text/javascript">
    $(function () {
        $("#sortablePlaylist").sortable();
        $("#sortablePlaylist").disableSelection();
    });    
</script>




<script type="text/javascript">

    var isMOUSE_UP_ON = false;
    var old_order = 0;

    function mouse_down(obj, link_id) {
        var index = $("#sortablePlaylist .srt_itm").index(obj);
        old_order = index;
    }

    function mouse_up(obj, song_id) {

        if (isMOUSE_UP_ON == true) {

            var new_order = $("#sortablePlaylist .srt_itm").index(obj);
            var set_order = (new_order - old_order);

            

            var randomnumber=Math.floor(Math.random()*1100000);
            $.ajax({
                type: "POST",
                url: "/playlist/applyOrder?SONG_ID=" + song_id + "&SONG_ORDER=" + set_order + "&ACTIVE_PL=" + @ViewBag.Playlist + "&Rnum=" + randomnumber,
                async: true,
                success: function (data) {
                    //alert(data);
                }
            });


            isMOUSE_UP_ON = false;
            old_order = 0;
        }
    }
</script>

Views/playlist/getPlaylistDetailsPlayer.cshtml
@model List<hypster_tv_DAL.PlaylistData_Song>
@{
    Layout = null;
}





@for (int i = 0; i < Model.Count; i++)
{
    <div id="PlItem_@i" class="playlistItemC" onclick="plVClick('@Model[i].YoutubeId', @i)" id="song_@Model[i].playlist_track_id" style=" float:left; width:98%; height:44px; overflow:hidden; background-color:#292929; margin:0 0 2px 2px;" >
                    
        <img alt="" src="http://i.ytimg.com/vi/@Model[i].YoutubeId/0.jpg" style="float:left; width:50px; height:37px; margin:4px 0 0 4px; border-radius:3px; cursor:pointer;" />

        <div style="float:left; width:290px; height:28px; line-height:28px; overflow:hidden; margin-left:10px; margin-top:4px; cursor:pointer; font-size:16px; color:#DEDEDE;">
            @Model[i].Title
        </div>
                        
    </div>
}

@if (Model.Count == 0)
{
    <div style="float:left; width:98%; height:23px; line-height:23px; overflow:hidden; margin:0px 4px 3px 4px; padding-left:3px; background-color:#454545; border-radius:2px; text-align:left; cursor:pointer; ">
        No songs in this playlist
    </div>
}





<script>

var items_arr = new Array();
@for (int i = 0; i < Model.Count; i++)
{
    <text>items_arr[@i] = '@Model[i].YoutubeId';</text>
}

if(items_arr.length > 1)
{
    $("#Prev_btn").css("display","block");
    $("#Next_btn").css("display","block");
    $("#Shuffle_btn").css("display","block");
}
else
{
    $("#Prev_btn").css("display","none");
    $("#Next_btn").css("display","none");
    $("#Shuffle_btn").css("display","none");
}



CURR_VIDEO = -1;

PlayNextVideo();

</script>  