ViewModels/GetPlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace hypster.ViewModels
{
    public class GetPlayerViewModel
    {
        
        public hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();
        public List<hypster_tv_DAL.Playlist> playlists_list = new List<hypster_tv_DAL.Playlist>();

        public hypster_tv_DAL.Player player = new hypster_tv_DAL.Player();


        public List<hypster_tv_DAL.MusicGenre> music_genres_list = new List<hypster_tv_DAL.MusicGenre>();



        public GetPlayerViewModel()
        {
        }



    }
}

Controllers/playerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hypster.Controllers
{

    //
    //this controller manages players wizards
    public class playerController : ControllerBase
    {

        


        //----------------------------------------------------------------------------------------------------------
        //[HttpGet]
        [Authorize]
        public ActionResult getPlayer(string id)
        {
            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.memberManagement memberManager = new hypster_tv_DAL.memberManagement();
            hypster_tv_DAL.playlistManagement playlistManager = new hypster_tv_DAL.playlistManagement();
            hypster_tv_DAL.playerManagement playerManager = new hypster_tv_DAL.playerManagement();
            //--------------------------------------------------------------------------------------------




            //--------------------------------------------------------------------------------------------
            hypster.ViewModels.GetPlayerViewModel model = new ViewModels.GetPlayerViewModel();
            model.curr_user = memberManager.getMemberByUserName(User.Identity.Name);
            model.playlists_list = playlistManager.GetUserPlaylists(model.curr_user.id);
            //--------------------------------------------------------------------------------------------





            //*******Check ACTION***********************************
            if (Request.QueryString["ACT"] != null)
            {
                switch (Request.QueryString["ACT"])
                {
                    case "DeletePlayer":
                        
                        int i_player_id = 0;
                        if (Request.QueryString["Pl_ID"] != null && Int32.TryParse(Request.QueryString["Pl_ID"], out i_player_id) == false)
                            i_player_id = 0;


                        if (i_player_id != 0)
                        {
                            playerManager.DeletePlayer(model.curr_user.id, i_player_id);
                            return RedirectPermanent("/account/music");
                        }

                        break;
                    default:
                        break;
                }
            }
            //******************************************************





            switch (id)
            {
                case "BarPlayer":
                    //get player for editing if exist
                    int player_ID1 = 0;
                    if (Request.QueryString["Pl_ID"] != null)
                    {
                        if(Int32.TryParse(Request.QueryString["Pl_ID"], out player_ID1) == false)
                            player_ID1 = 0;
                        if(player_ID1 != 0)
                            model.player = playerManager.GetPlayerByID(model.curr_user.id, player_ID1);
                    }
                    
                    
                    return View("getPlayer_Bar", model);
                    break;

                case "ClassicPlayer":
                    //get player for editing if exist
                    int player_ID2 = 0;
                    if (Request.QueryString["Pl_ID"] != null)
                    {
                        if(Int32.TryParse(Request.QueryString["Pl_ID"], out player_ID2) == false)
                            player_ID2 = 0;
                        if(player_ID2 != 0)
                            model.player = playerManager.GetPlayerByID(model.curr_user.id, player_ID2);
                    }

                    return View("getPlayer_Classic", model);
                    break;


                case "RadioPlayer":
                    //get player for editing if exist

                    hypster.ViewModels.GetPlayerViewModel model_Radio = new ViewModels.GetPlayerViewModel();

                    int player_ID3 = 0;
                    if (Request.QueryString["Pl_ID"] != null)
                    {
                        if (Int32.TryParse(Request.QueryString["Pl_ID"], out player_ID3) == false)
                            player_ID3 = 0;
                        if (player_ID3 != 0)
                            model_Radio.player = playerManager.GetPlayerByID(model.curr_user.id, player_ID3);
                    }

                    hypster_tv_DAL.MemberMusicGenreManager genreMeneger = new hypster_tv_DAL.MemberMusicGenreManager();
                    model_Radio.music_genres_list = genreMeneger.GetMusicGenresList();

                    return View("getPlayer_Radio", model_Radio);
                    break;

                default:
                    break;

            }


            return View();
        }
        //----------------------------------------------------------------------------------------------------------








        // FORM FOR BAR PLAYER
        //----------------------------------------------------------------------------------------------------------
        [HttpPost]
        [Authorize]
        public ActionResult getPlayer_barPlayer(int PlayerID, string PlayerName, int? Sel_Playlist_ID, bool BAR_autostart, bool BAR_shufflePlayback, string Placement_of_the_Player, bool BAR_showPlaylistByDefault, string Player_Color_Scheme)
        {
            //--------------------------------------------------------------------------------------------
            if (Sel_Playlist_ID == null)
                return RedirectPermanent("/create");
            //--------------------------------------------------------------------------------------------



            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.playerManagement playerManager = new hypster_tv_DAL.playerManagement();
            hypster_tv_DAL.memberManagement memberManager = new hypster_tv_DAL.memberManagement();
            //--------------------------------------------------------------------------------------------




            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();
            curr_user = memberManager.getMemberByUserName(User.Identity.Name);


            hypster_tv_DAL.Player player = new hypster_tv_DAL.Player();
            player.user_ID = curr_user.id;
            player.Player_Type = "BarPlayer";


            player.player_Name = PlayerName;
            player.playlist_ID = Sel_Playlist_ID;
            player.BAR_playerSkin = Player_Color_Scheme;
            player.BAR_autostart = BAR_autostart;
            player.BAR_shufflePlayback = BAR_shufflePlayback;
            player.BAR_placementOfThePlayer = Placement_of_the_Player;
            player.BAR_showPlaylistByDefault = BAR_showPlaylistByDefault;



            //save only if player_id null - new player
            if (PlayerID == 0)
            {
                playerManager.hyDB.Players.AddObject(player);
                playerManager.hyDB.SaveChanges();
            }
            else //edit player
            {   
                if (PlayerID != 0)
                {   
                    hypster_tv_DAL.Player player_edit = new hypster_tv_DAL.Player();
                    player_edit = playerManager.GetPlayerByID(curr_user.id, PlayerID);

                    player_edit.player_Name = player.player_Name;
                    player_edit.playlist_ID = player.playlist_ID;
                    player_edit.BAR_playerSkin = player.BAR_playerSkin;
                    player_edit.BAR_autostart = player.BAR_autostart;
                    player_edit.BAR_shufflePlayback = player.BAR_shufflePlayback;
                    player_edit.BAR_placementOfThePlayer = player.BAR_placementOfThePlayer;
                    player_edit.BAR_showPlaylistByDefault = player.BAR_showPlaylistByDefault;

                    playerManager.EditPlayer(player_edit);

                    //returns edited player
                    return View("getPlayer_Bar_Code", player_edit);
                }
            }
            //--------------------------------------------------------------------------------------------




            //if here - returns new player
            return View("getPlayer_Bar_Code", player);
        }
        //----------------------------------------------------------------------------------------------------------


        /*

        //public getPlayer_classicPlayer
        //----------------------------------------------------------------------------------------------------------
        [HttpPost]
        [Authorize]
        public ActionResult getPlayer_classicPlayer(int PlayerID, string PlayerName, int? Sel_Playlist_ID, bool CLASSIC_autostart, bool CLASSIC_shufflePlayback, string Player_Color_Scheme)
        {
            //need to log this case
            //--------------------------------------------------------------------------------------------
            if (Sel_Playlist_ID == null)
                return RedirectPermanent("/create");
            //--------------------------------------------------------------------------------------------



            // 1.genral declarations
            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.playerManagement playerManager = new hypster_tv_DAL.playerManagement();
            hypster_tv_DAL.memberManagement memberManager = new hypster_tv_DAL.memberManagement();
            //--------------------------------------------------------------------------------------------





            //--------------------------------------------------------------------------------------------
            hypster_tv_DAL.Member curr_user = new hypster_tv_DAL.Member();

Views/player/getPlayer.cshtml
@{
    ViewBag.Title = "Hypster - free music online - player for tumblr";
    ViewBag.Desc = "";
    Layout = null;
}



<!-- *************************************CONTENT************************************* -->
<div style=" float:left; width:1000px; margin:15px 0 15px 15px; " >


    <div style=" float:left; width:100%; margin-top:13px;">
    
        <div onclick="LoadPlayerCont('/player/getPlayer/BarPlayer');" style=" float:left; margin:0 0 0 0px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/bar_widget.png"  />
            <div style=" font-size:17px; color:#FCF088;">Bar player</div>
        </div>


        <div onclick="LoadPlayerCont('/player/getPlayer/ClassicPlayer');" style=" float:left; margin:0 0 0 20px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/widget_1.png" />
            <div style=" font-size:17px; color:#FCF088;">Classic player</div>
        </div>


        <div onclick="LoadPlayerCont('/player/getPlayer/RadioPlayer');" style=" float:left; margin:0 0 0 20px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/widget_radio.png"  />
            <div style=" font-size:17px; color:#FCF088;">Radio player</div>
        </div>

        <!--div onclick="window.location='/hypster/New_Player_For_Tumblr_Code';" style=" float:left; margin:0 0 0 20px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/new_widget.png"  />
            <div style=" font-size:17px; color:#FCF088;">New player</div>
        </div-->

        <!--div onclick="window.location='/hypster/New_Player_For_Tumblr_Code_1';" style=" float:left; margin:10px 0 0 0px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/new_widget_1.png"  />
            <div style=" font-size:17px; color:#FCF088;">New player 1</div>
        </div-->

        <!--div onclick="window.location='/hypster/New_Player_For_Tumblr_Code_2';" style=" float:left; margin:10px 0 0 20px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
            <img alt="" src="/imgs/get_player/new_widget_2.png"  />
            <div style=" font-size:17px; color:#FCF088;">New player 2</div>
        </div-->


    </div>


</div>
<!-- *************************************CONTENT************************************* -->

Views/player/getPlayer_Bar.cshtml
@model hypster.ViewModels.GetPlayerViewModel
@{
    ViewBag.Title = "Hypster - Bar player";
    ViewBag.Desc = "";
    Layout = null;
}


<div style=" float:left; width:1024px; margin:15px 0 15px 15px; " >


    <div style=" float:left; width:100%; height:40px; overflow:hidden; background-color:#232323; border-radius:2px; margin-top:0px; ">
        <h2 style=" float:left; margin:3px 0px 0px 15px; color:#FFFFFF; font:23px/1.5 Hypster-Font,Arial,sans-serif;">
            Bar player
        </h2>
    </div>



    <div style=" float:left; width:100%; border-radius:2px; margin-top:15px; ">
   
        @using (Html.BeginForm("getPlayer_barPlayer", "player"))
        {
            <div style=" float:left; width:565px;">

                <div style=" float:left; width:220px; height:220px; margin:0 0 0 0px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
                    @if (Model.player.BAR_playerSkin != "")
                    {
                        <img id="skinImgHolder1" alt="" src="/imgs/get_player/bar_skins/@(Model.player.BAR_playerSkin).png"  />
                    }
                    else
                    {
                        <img id="skinImgHolder1" alt="" src="/imgs/get_player/bar_skins/tunes.png"  />
                    }
                </div>

            
                <div style=" float:left; width:300px; height:220px; line-height:25px; margin:0 0 0 13px; border:7px solid #232323; background-color:#232323; text-align:right;">
            
                    Name: <input id="PlayerName" name="PlayerName" type="text" maxlength="50" style=" width:215px;" value="@Model.player.player_Name" />
                    <br />
            
                    Playlist: 
                    <select id="Sel_Playlist_ID" name="Sel_Playlist_ID" style=" width:220px; height:22px; margin-top:2px;" onchange="playlist_changed(this);"> 
                        @foreach (var item in Model.playlists_list)
                        {
                            <option value="@item.id" @if (Model.player.playlist_ID == item.id)
                                                     {<text>selected="selected"</text>}>@item.name</option>
                        }
                    </select>
                    <br />

                    Autostart: @Html.CheckBox("BAR_autostart", (bool)Model.player.BAR_autostart) 
                    <br />
                    Shuffle Playback: @Html.CheckBox("BAR_shufflePlayback", (bool)Model.player.BAR_shufflePlayback) 
                    <br />


                    Placement of the Player: 
                    <select id="Placement_of_the_Player" name="Placement_of_the_Player" style=" width:150px; height:22px; margin-top:2px;"> 
                        <option value="bottom" @if (Model.player.BAR_placementOfThePlayer == "bottom")
                                               {<text>selected="selected"</text>}>bottom</option>
                        <option value="top" @if (Model.player.BAR_placementOfThePlayer == "top")
                                            {<text>selected="selected"</text>}>top</option>
                    </select>
                    <br />

                    Show Playlist by Default: @Html.CheckBox("BAR_showPlaylistByDefault", (bool)Model.player.BAR_showPlaylistByDefault)
                    <br />


                    Player Color Scheme: 
                    <select id="Player_Color_Scheme" name="Player_Color_Scheme" onchange="preview_skin_bar(this.value);" style=" width:150px; height:22px; margin-top:2px;"> 
                        <option value="tunes" @if (Model.player.BAR_playerSkin == "tunes")
                                               {<text>selected="selected"</text>} >Tunes</option>

                        <option value="aquaBlue" @if (Model.player.BAR_playerSkin == "aquaBlue")
                                            {<text>selected="selected"</text>} >Aqua Blue</option>

                        <option value="aquaPurple" @if (Model.player.BAR_playerSkin == "aquaPurple")
                                            {<text>selected="selected"</text>} >Aqua Purple</option>

                        <option value="aquaPink" @if (Model.player.BAR_playerSkin == "aquaPink")
                                            {<text>selected="selected"</text>} >Aqua Pink</option>

                        <option value="aquaOrange" @if (Model.player.BAR_playerSkin == "aquaOrange")
                                            {<text>selected="selected"</text>} >Aqua Orange</option>

                        <option value="aquaGreen" @if (Model.player.BAR_playerSkin == "aquaGreen")
                                            {<text>selected="selected"</text>} >Aqua Green</option>

                        <option value="cyber" @if (Model.player.BAR_playerSkin == "cyber")
                                            {<text>selected="selected"</text>} >Cyber</option>

                        <option value="black" @if (Model.player.BAR_playerSkin == "black")
                                            {<text>selected="selected"</text>} >Black</option>

                        <option value="blue" @if (Model.player.BAR_playerSkin == "blue")
                                            {<text>selected="selected"</text>} >Blue</option>

                        <option value="purple" @if (Model.player.BAR_playerSkin == "purple")
                                            {<text>selected="selected"</text>} >Purple</option>

                        <option value="pink" @if (Model.player.BAR_playerSkin == "pink")
                                            {<text>selected="selected"</text>} >Pink</option>

                        <option value="orange" @if (Model.player.BAR_playerSkin == "orange")
                                            {<text>selected="selected"</text>} >Orange</option>

                        <option value="green" @if (Model.player.BAR_playerSkin == "green")
                                            {<text>selected="selected"</text>} >Green</option>
                    </select>


                    <input type="hidden" id="PlayerID" name="PlayerID" value="@Model.player.player_ID" />
                </div>
            
            
                <input type="submit" value="GET CODE" style=" float:left; width:425px; height:30px; line-height:25px; border-radius:2px; background-color:#42606e; color:#FCF088; margin:15px 0 0 0; cursor:pointer; font-weight:bold;" />
                <input type="button" value="CANCEL" onclick="window.location='/create/player';" style=" float:left; width:120px; height:30px; line-height:25px; border-radius:2px; background-color:#42606e; color:#FFFFFF; margin:15px 0 0 15px; cursor:pointer;" />

            </div>
            




            <div id="PlaylistSongsContainer" style=" float:left; width:430px; min-height:220px; line-height:25px; margin-left:13px; border:7px solid #232323; background-color:#232323; border-radius:2px; text-align:right;">
                
                <script type="text/javascript">
                    $(document).ready(
                        function () {
                            var object = document.getElementById('Sel_Playlist_ID');
                            playlist_changed(object);
                        });
                </script>

            </div>


        
        }
    </div>


</div>

Views/player/getPlayer_Bar_Code.cshtml
@model hypster_tv_DAL.Player
@{
    ViewBag.Title = "Hypster - Bar player";
    ViewBag.Desc = "";
}



<script type="text/javascript">

    $(document).ready(function () {

        if ($(window).width() > 1024) {
            var margin_left = $(window).width() - 1024 - 30;
            var cont_width = 1024 + 30 + (margin_left / 2) - 15;

            $("#listenSlide1").css("float", "right");
            $("#listenSlide1").css("width", cont_width + "px");

        }


    });

    $(window).resize(function () {
        if ($(window).width() > 1024) {
            var margin_left = $(window).width() - 1024 - 30;
            var cont_width = 1024 + 30 + (margin_left / 2) - 15;

            $("#listenSlide1").css("float", "right");
            $("#listenSlide1").css("width", cont_width + "px");

        }
    });
</script>






<div class="boxContRight">
    <div id="listenSlide1" style="width:1024px; min-height:400px; padding:15px 0 15px 15px; background-color:#313537; margin:0 auto 0 auto; border-radius:2px; ">




                <div style=" float:left; width:950px; margin:15px 0 15px 15px;" >

                    <div style=" float:left; width:100%; min-height:300px; overflow:hidden; background:#555555 url('/imgs/box_back.png') repeat; border-radius:2px; margin-top:0px; ">
    
    
                        <div style=" float:left; width:100%; text-align:left; margin-top:10px;">
                            
                            <h2 style=" float:left; width:98%; margin-left:2%; margin-bottom:0px; color:#FCF088; font:23px/1.5 Hypster-Font,Arial,sans-serif;">
                                Copy and Paste code on your website
                            </h2>

                            <div style=" float:left; width:98%; margin-left:2%; color:#FCF088; font-size:16px;">
                                Please paste the following code under beginning of &lt;body&gt; tag (i.e. on top of webpage content). <br />
                                Note: This code will only work on blogs and websites. This will not work on myspace/facebook/twitter/tagged/friendster. <br />
                            </div>
                        </div>


                        <textarea id="PlayerCodeArea" style=" width:96%; margin:2%; height:300px;">
                            <!--Hypster Music Player-->
                            <script type="text/javascript" src="http://scm.hypster.com/script.php" ><!--//--></script>
                            <script type="text/javascript">
                            <!--
                                SCMMusicPlayer.init("{'skin':'skins/@Model.BAR_playerSkin/skin.css','playback':{'autostart':'@(Model.BAR_autostart.ToString().ToLower())','shuffle':'@Model.BAR_shufflePlayback.ToString().ToLower()','volume':'100'},'playlist':'@Model.playlist_ID','placement':'@Model.BAR_placementOfThePlayer','showplaylist':'@Model.BAR_showPlaylistByDefault.ToString().ToLower()'}");
                            //-->
                            </script>
                            <!--Hypster Music Player-->
                        </textarea>


                        <div style=" float:left; width:100%; margin-bottom:10px;">
                            <div onclick="window.location='/account/music';" style="float:left; width:190px; height:23px; line-height:23px; margin:5px 4px 3px 17px; padding-left:3px; background-color:#42606e; color:#FFFFFF; border-radius:2px; text-align:center; cursor:pointer; ">
                                Go to my players
                            </div>
                        </div>



                    </div>

                </div>

    

    </div>
</div>

Views/player/getPlayer_Classic_Code_Custom.cshtml
@model hypster_tv_DAL.Player
@{
    ViewBag.Title = "Hypster - Classic custom player";
    ViewBag.Desc = "";
}





<script type="text/javascript">

    $(document).ready(function () {

        if ($(window).width() > 1024) {
            var margin_left = $(window).width() - 1024 - 30;
            var cont_width = 1024 + 30 + (margin_left / 2) - 15;

            $("#listenSlide1").css("float", "right");
            $("#listenSlide1").css("width", cont_width + "px");
        }

    });

    $(window).resize(function () {
        if ($(window).width() > 1024) {
            var margin_left = $(window).width() - 1024 - 30;
            var cont_width = 1024 + 30 + (margin_left / 2) - 15;

            $("#listenSlide1").css("float", "right");
            $("#listenSlide1").css("width", cont_width + "px");
        }
    });
</script>





<div class="boxContRight">
    <div id="listenSlide1" style="width:1024px; min-height:400px; padding:15px 0 15px 15px; background-color:#313537; margin:0 auto 0 auto; border-radius:2px; ">



            <div style=" float:left; width:950px; margin:15px 0 15px 15px;" >

                <div style=" float:left; width:100%; min-height:300px; overflow:hidden; background:#555555 url('/imgs/box_back.png') repeat; border-radius:2px; margin-top:0px; ">


                    <div style=" float:left; width:100%; text-align:left; margin-top:10px;">
                        
                        <h2 style=" float:left; width:98%; margin-left:2%; margin-bottom:0px; color:#FCF088; font:23px/1.5 Hypster-Font,Arial,sans-serif;">
                            Copy and Paste code on your website
                        </h2>

                        <div style=" float:left; width:98%; margin-left:2%; color:#FCF088; font-size:16px;">
                            Please paste the following code between &lt;body&gt; &lt;/body&gt; tags <br />
                        </div>

                    </div>


                    <textarea id="PlayerCodeArea" style=" width:96%; margin:2%; height:300px;">
            
                            <embed quality="high" style="width:@(ViewBag.Custom_Size_Sel_W)px; visibility:visible; height:@(ViewBag.Custom_Size_Sel_H)px;" type="application/x-shockwave-flash" height="@(ViewBag.Custom_Size_Sel_W)" width="@(ViewBag.Custom_Size_Sel_H)"  pluginspage="http://www.macromedia.com/go/getflashplayer" border="0" src="http://www.hypster.com/flash/player.swf?id=@(Model.user_ID):@(Model.playlist_ID):@if (Model.CLASSIC_shufflePlayback.Value == true){<text>1</text>}else{<text>0</text>}&autoplay=@if (Model.CLASSIC_autostart.Value == true){<text>true</text>}else{<text>false</text>}" FlashVars="color_bg=0x@(ViewBag.hf_BackgroundColor)&color_border=0x9A0000&color_box=0x9A0000&color_songbg=0x@(ViewBag.hf_SongBackground)&color_song_clicked=0x@(ViewBag.hf_SongClicked)&color_Title=0x000000&color_btns=0x@(ViewBag.hf_Buttons)&color_title=0x000000" />
                            <br />
                            <a href="http://www.hypster.com/?src=player-text" style="font-weight:bold;font-size:12px">Get Your Own Free Hypster.com Playlist.</a>
                        
                    </textarea>

                </div>

            </div>



</div>
</div>

Views/player/getPlayer_Radio.cshtml
@model hypster.ViewModels.GetPlayerViewModel
@{
    ViewBag.Title = "Hypster - Radio player";
    ViewBag.Desc = "";
    Layout = null;
}



<div style=" float:left; width:1024px; margin:15px 0 15px 15px;" >


    <div style=" float:left; width:100%; height:40px; overflow:hidden; background-color:#232323; border-radius:2px; margin-top:0px; ">
        <h2 style=" float:left; margin:3px 0px 0px 15px; color:#FFFFFF; font:23px/1.5 Hypster-Font,Arial,sans-serif;">
            Radio player
        </h2>
    </div>



    <div style=" float:left; width:100%; border-radius:2px; margin-top:15px; ">
    
        @using (Html.BeginForm("getPlayer_radioPlayer", "player"))
        {
            <div style=" float:left; width:565px;">
        
                    <div style=" float:left; width:220px; height:220px; margin:0 0 0 0px; border:7px solid #232323; background-color:#232323; border-radius:2px; cursor:pointer;">
                
                        <img id="skinImgHolder1" alt="" src="/imgs/get_player/widget_radio.png"  />
                
                    </div>



                    <div style=" float:left;  width:300px; height:220px; line-height:25px; margin:0 0 0 13px; border:7px solid #232323; background-color:#232323; border-radius:2px; text-align:right;">
            
                        Name: <input id="PlayerName" name="PlayerName" type="text" maxlength="50" style=" width:215px;" value="@Model.player.player_Name" />
                        <br />
            
                        Genre: 
                        <select id="Sel_Genre_ID" name="Sel_Genre_ID" style=" width:220px; height:22px; margin-top:2px;"> 
                        @foreach (var item in Model.music_genres_list)
                        {
                            <option value="@item.Genre_ID" @if (Model.player.RADIO_Genre_ID == item.Genre_ID)
                                                         {<text>selected="selected"</text>}>@item.GenreName</option>
                        }
                        </select>
                        <br />


                        Autostart: @Html.CheckBox("RADIO_autostart", (bool)Model.player.RADIO_autostart)
                

                        <input type="hidden" id="PlayerID" name="PlayerID" value="@Model.player.player_ID" />
                    </div>


                    <input type="submit" value="GET CODE" style=" float:left; width:425px; height:30px; line-height:25px; border-radius:2px; background-color:#42606e; color:#FCF088; margin:15px 0 0 0; cursor:pointer; font-weight:bold;" />
                    <input type="button" value="CANCEL" onclick="window.location='/create/player';" style=" float:left; width:120px; height:30px; line-height:25px; border-radius:2px; background-color:#42606e; color:#FFFFFF; margin:15px 0 0 15px; cursor:pointer;" />

            </div>


            <div id="PlaylistSongsContainer" style=" float:left; width:430px; min-height:220px; line-height:25px; margin-left:13px; border:7px solid #232323; background-color:#232323; border-radius:2px; text-align:right;">
            </div>


         

        
            
        
        }

    </div>

</div>